//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class binaryProduct_Ulke_Raporu
    {
        public int binaryProductID { get; set; }
        public string binaryProductNo { get; set; }
        public string binaryProductYil { get; set; }
        public string binaryProductIthalat { get; set; }
        public string binaryProductIhracat { get; set; }
    }
}
