//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ozel_Ulke_Raporu
    {
        public int ozelUlkeID { get; set; }
        public Nullable<int> UlkeID { get; set; }
        public string yil { get; set; }
        public Nullable<long> ithalat { get; set; }
        public Nullable<long> ihracat { get; set; }
        public Nullable<long> hacim { get; set; }
        public Nullable<long> denge { get; set; }
    }
}
