//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Ulke_Raporu
    {
        public int productID { get; set; }
        public string productNo { get; set; }
        public string productYil { get; set; }
        public string productIthalat { get; set; }
        public string productIhracat { get; set; }
    }
}
