//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Base_GenelUlkeRaporu
    {
        public int genelUlkeID { get; set; }
        public Nullable<int> UlkeID { get; set; }
        public string yil { get; set; }
        public Nullable<int> IthalatUlkeID { get; set; }
        public Nullable<int> ithalat { get; set; }
        public Nullable<int> IhracatUlkeID { get; set; }
        public Nullable<int> ihracat { get; set; }
    }
}
